version: '3.6'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
# version: '3.6'

# services:
#   web:
#     build: .
#     volumes:
#       - ./:/app
#     working_dir: /app
#     command: puma
#     ports:
#       - 3000:3000
#     depends_on:
#       - db
#     environment:
#       DATABASE_URL: postgres://postgres@db
#   db:
#     image: postgres:10.3-alpine